### ISSUE TITLE
How about using HTML5 imports ?

### ISSUE THREAD

**Issue by squareguy** [Xeoncross/jr#26]
Benefits:
- Decreased load time since the browser would cache and the import file.
- Easy website templating.
- JS would only be required to parse Markdown.

Reference :
- [html5rocks.com](http://www.html5rocks.com/en/tutorials/webcomponents/imports/)

**Comment by misterhtmlcss** [comment]
Hi Squareguy, HTML5 imports is only supported by 50% of browsers making it unsuitable for a platform that uses the client side browser to do all the work rather than the server.
